version: '3.8'
services:
  core-banking-system:
    image: wiremock/wiremock:3.5.4
    container_name: core-banking-system
    volumes:
      - ./wiremock:/home/wiremock
    ports:
      - "8081:8080"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  database:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=card-service